from django.db import models
from django.utils import timezone

class Enfermeros(models.Model):
    DNI = models.CharField(max_length=8)
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    direccion = models.TextField()
    email = models.EmailField()
    fecha_nacimiento=models.DateField()
    genero=models.CharField(max_length=12, default='masculino')
    telefono = models.CharField(max_length=12)
    lunesMI = models.TimeField(null=True)
    lunesMF = models.TimeField(null=True)
    lunesTI = models.TimeField(null=True)
    lunesTF = models.TimeField(null=True)
    martesMI = models.TimeField(null=True)
    martesMF = models.TimeField(null=True)
    martesTI = models.TimeField(null=True)
    martesTF = models.TimeField(null=True)
    miercolesMI = models.TimeField(null=True)
    miercolesMF = models.TimeField(null=True)
    miercolesTI = models.TimeField(null=True)
    miercolesTF = models.TimeField(null=True)
    juevesMI = models.TimeField(null=True)
    juevesMF = models.TimeField(null=True)
    juevesTI = models.TimeField(null=True)
    juevesTF = models.TimeField(null=True)
    viernesMI = models.TimeField(null=True)
    viernesMF = models.TimeField(null=True)
    viernesTI = models.TimeField(null=True)
    viernesTF = models.TimeField(null=True)
    sabadoMI = models.TimeField(null=True)
    sabadoMF = models.TimeField(null=True)
    sabadoTI = models.TimeField(null=True)
    sabadoTF = models.TimeField(null=True)
    domingoMI = models.TimeField(null=True)
    domingoMF = models.TimeField(null=True)
    domingoTI = models.TimeField(null=True)
    domingoTF = models.TimeField(null=True)


class Salas(models.Model):
    nombre=models.CharField(max_length=50)
    tipo_sala=models.CharField(max_length=50)
# Create your models here.
class Paciente(models.Model):
    DNI = models.CharField(max_length=8)
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    direccion = models.TextField()
    email = models.EmailField()
    obra_social=models.CharField(max_length=30)
    fecha_nacimiento=models.DateField(null=True)
    genero=models.CharField(max_length=12, default='masculino')
    telefono = models.CharField(max_length=12)  # Puedes ajustar el patrón de validación según tu necesidad
    alergia = models.CharField(max_length=255, blank=True, null=True)
    enfermedad_cronica = models.CharField(max_length=255, blank=True, null=True)
    tratamiento_medico = models.CharField(max_length=255, blank=True, null=True)
    enfermedades_o_cirugias = models.TextField(blank=True, null=True)
    enfermero=models.ForeignKey(Enfermeros,on_delete=models.CASCADE)
    internado=models.BooleanField(default=False)
    sala=models.ForeignKey(Salas,on_delete=models.CASCADE)


class Medico(models.Model):
    DNI=models.CharField(max_length=8)
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=100)
    matricula=models.CharField(max_length=10)
    direccion = models.TextField()
    email = models.EmailField()
    telefono = models.CharField(max_length=12) 
    estado=models.BooleanField(default=False)
    especialidad=models.CharField(max_length=100)
    lunesMI = models.TimeField(null=True)
    lunesMF = models.TimeField(null=True)
    lunesTI = models.TimeField(null=True)
    lunesTF = models.TimeField(null=True)
    martesMI = models.TimeField(null=True)
    martesMF = models.TimeField(null=True)
    martesTI = models.TimeField(null=True)
    martesTF = models.TimeField(null=True)
    miercolesMI = models.TimeField(null=True)
    miercolesMF = models.TimeField(null=True)
    miercolesTI = models.TimeField(null=True)
    miercolesTF = models.TimeField(null=True)
    juevesMI = models.TimeField(null=True)
    juevesMF = models.TimeField(null=True)
    juevesTI = models.TimeField(null=True)
    juevesTF = models.TimeField(null=True)
    viernesMI = models.TimeField(null=True)
    viernesMF = models.TimeField(null=True)
    viernesTI = models.TimeField(null=True)
    viernesTF = models.TimeField(null=True)
    sabadoMI = models.TimeField(null=True)
    sabadoMF = models.TimeField(null=True)
    sabadoTI = models.TimeField(null=True)
    sabadoTF = models.TimeField(null=True)
    domingoMI = models.TimeField(null=True)
    domingoMF = models.TimeField(null=True)
    domingoTI = models.TimeField(null=True)
    domingoTF = models.TimeField(null=True)


class Llamados(models.Model):
    tipo_llamado=models.CharField(max_length=20)
    fecha_hora=models.DateTimeField(default=timezone.now)
    id_paciente=models.ForeignKey(Paciente,on_delete=models.CASCADE)
    id_zona=models.ForeignKey(Salas,on_delete=models.CASCADE)
    id_medico=models.ForeignKey(Medico,on_delete=models.CASCADE)

class User(models.Model):
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=100)
    telefono=models.CharField(max_length=15)
    email=models.EmailField()
    contraseña=models.CharField(max_length=50 )
    tipo_user=models.BooleanField(default=False)

