# Generated by Django 4.2.5 on 2023-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='llamados',
            name='tipo_llamado',
            field=models.CharField(max_length=20),
        ),
    ]
