# Generated by Django 4.2.5 on 2023-10-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamados',
            name='ubicacion',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='llamados',
            name='id_medico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitio.medico'),
        ),
        migrations.AlterField(
            model_name='llamados',
            name='id_paciente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitio.paciente'),
        ),
        migrations.AlterField(
            model_name='llamados',
            name='id_zona',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitio.salas'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermero',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitio.enfermeros'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sala',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitio.salas'),
        ),
    ]
