# Generated by Django 4.2.5 on 2023-10-03 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='enfermero',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sitio.enfermeros'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sala',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sitio.salas'),
        ),
    ]
