# Generated by Django 4.2.5 on 2023-10-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_remove_user_direccion_alter_llamados_tipo_llamado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='enfermedades_o_cirugias',
            new_name='cirugias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='matricula',
        ),
        migrations.AddField(
            model_name='paciente',
            name='Salas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.salas'),
        ),
        migrations.AlterField(
            model_name='llamados',
            name='id_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.salas'),
        ),
        migrations.DeleteModel(
            name='Zonas',
        ),
    ]
