# Generated by Django 4.2.5 on 2023-10-03 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_alter_paciente_enfermero_alter_paciente_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='enfermero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitio.enfermeros'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitio.salas'),
        ),
    ]
