# Generated by Django 4.2.5 on 2023-10-02 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_enfermeros_domingomf_enfermeros_domingomi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamados',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
