# Generated by Django 4.2.5 on 2023-10-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_alter_llamados_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sitio.salas'),
            preserve_default=False,
        ),
    ]
