# Generated by Django 4.2.5 on 2023-09-20 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_paciente_alergia_paciente_bajo_tratamiento_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='bajo_tratamiento_medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ha_tenido_enfermedades_o_cirugias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tiene_alergia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tiene_enfermedad_cronica',
        ),
    ]
