# Generated by Django 4.2.5 on 2023-09-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_remove_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='bajo_tratamiento_medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ha_tenido_enfermedades_o_cirugias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tiene_alergia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tiene_enfermedad_cronica',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
