# Generated by Django 4.2.5 on 2023-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_paciente_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='internado',
            field=models.CharField(default='No', max_length=2),
        ),
    ]
