# Generated by Django 4.2.5 on 2023-09-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_remove_paciente_bajo_tratamiento_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
