# Generated by Django 4.2.5 on 2023-09-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_logentry_user'),
        ('sitio', '0005_customuser_remove_customuser1_groups_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='auth.permission'),
        ),
    ]
