# Generated by Django 4.2.5 on 2023-10-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_alter_paciente_internado'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='genero',
            field=models.CharField(default='Masculino', max_length=12),
        ),
    ]
