# Generated by Django 4.2.5 on 2023-10-02 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_medico_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
