# Generated by Django 4.2.5 on 2023-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_medico_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergia',
            field=models.CharField(blank=True, default='No', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, default='No', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermedades_o_cirugias',
            field=models.TextField(blank=True, default='No', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tratamiento_medico',
            field=models.CharField(blank=True, default='No', max_length=255, null=True),
        ),
    ]
