# Generated by Django 4.2.5 on 2023-10-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_alter_paciente_alergia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='enfermedades_o_cirugias',
            field=models.TextField(blank=True, default='No', max_length=255),
        ),
    ]
