# Generated by Django 4.2.5 on 2023-09-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
