# Generated by Django 4.2.5 on 2023-10-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_alter_paciente_alergia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamados',
            name='diagnostico',
            field=models.CharField(default='nada', max_length=50),
        ),
    ]
