# Generated by Django 4.2.5 on 2023-10-03 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0011_alter_paciente_alergia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Medico', 'Médico'), ('Enfermero', 'Enfermero'), ('Recepcionista', 'Recepcionista')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='llamados',
            name='diagnostico',
            field=models.CharField(default='nada', max_length=50),
        ),
        migrations.AddField(
            model_name='llamados',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
