# Generated by Django 4.2.5 on 2023-10-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_llamados_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamados',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
