# Generated by Django 4.2.5 on 2023-10-02 22:41

from django.db import migrations, models
from django.contrib.auth.models import User,Group
def asignar_usuarios_a_grupos(apps, schema_editor):
    # Obtener los modelos de usuario y grupo
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')

    # Obtener o crear los grupos necesarios
    grupo_medicos, creado = Group.objects.get_or_create(name='Médicos')
    grupo_enfermeros, creado = Group.objects.get_or_create(name='Enfermeros')
    grupo_recepcionistas, creado = Group.objects.get_or_create(name='Recepcionistas')

class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_llamados_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamados',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(asignar_usuarios_a_grupos),
    ]
