# Generated by Django 4.2.5 on 2023-09-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_alter_paciente_genero'),
        ('sitio', '0012_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
    ]
